#!/usr/bin/env python

import datetime, os, sys
import psycopg2

dbhost      = "localhost"
dbname      = "mail"
dbuser      = "mailadm"

connstring = "dbname=%s user=%s host=%s password='none'" % (dbname,dbuser,dbhost)

def get_gid():
    """ Auxiliary function. Returns ID of 'mail' group in the system.
    """
    cmd = 'id -g mail'
    data = os.popen(cmd)
    return data.readline().strip()

def get_free_uid():
    """ Auxiliary function. Returns next unused virtual UID for mail user.
    """
    query = "SELECT COALESCE(MAX(uid)+1,1001) as uid FROM users"
    curs.execute(query)
    rows = curs.fetchone()
    return rows[0]

def adduser(email, password):
    uname, domain = email.split('@')
    uid = str(get_free_uid())
    gid = str(get_gid())
    query = "INSERT INTO users (email,passwd,uid,gid,maildir,enabled,quota) VALUES ('%s','%s',%s,%s,'/var/spool/mail/%s/%s/',1,0)" % (email, password, uid, gid, domain, uname)
    curs.execute(query)
    conn.commit()

def deluser(email):
    query = "DELETE FROM users WHERE email='%s'" % (email)
    curs.execute(query)
    conn.commit()

def listusers():
    query = "SELECT email, uid, maildir FROM users"
    curs.execute(query)
    rows = curs.fetchall()
    return rows
    
try:
    conn = psycopg2.connect(connstring)
except:
    sys.exit("I am unable to connect to the database %s on %s.") % (dbname, dbhost)
curs = conn.cursor()

args = sys.argv

if len(args) < 2:
    print """
    Usage: mailadm -list
           mailadm -add email password
           mailadm -del email
    """
else:
    if args[1].lower()=='-add':
	adduser(args[2], args[3])
    elif args[1].lower()=='-del':
	deluser(args[2])
    elif args[1].lower()=='-list':
	users = listusers()
	if len(users) > 0:
	    print "Email:" + "\t\t\t\t | " + "UID:" + "\t | " + "Maildir:"
	    print "-" * 80
	    for user in users:
		print user[0]+"\t\t | "+ str(user[1]) + "\t | " + user[2]
	else: 
	    print "No email accounts found in database!"


